### ISSUE TITLE
ms option bug

### ISSUE THREAD

**Issue by AL280** [snipesharp/snipesharp#1]
,

**Comment by dement6d** [comment]
> i cant click on ms in the options

im not sure if i understand the issue youre facing, can you be more specific?
1. what did you try doing
2. what happened
3. what did you expect to happen

if you want to know how to configure PacketSpreadMs in the config file, take a look [here](https://github.com/snipesharp/snipesharp/wiki/How-do-I-configure-snipesharp%3F-(How-to-edit-the-.json-files))
if you set your offset and are trying to change it after you've set it, you cant. you have to restart the program to change the offset
