### ISSUE TITLE
Unreasonable words within the program

### ISSUE THREAD

**Issue by SagMeinenNamen** [snipesharp/snipesharp#3]
The class FunnyErrors contains unreasonable words which should be replaced immediatly.

**Comment by dement6d** [comment]
Hi, I'm not sure what you mean by "unreasonable words", could you be more descriptive?

**Comment by SagMeinenNamen** [comment]
https://github.com/snipesharp/snipesharp/blob/main/src/Cli/Templates/FunnyErrors.cs

**Comment by dement6d** [comment]
> https://github.com/snipesharp/snipesharp/blob/main/src/Cli/Templates/FunnyErrors.cs

Could you be more specific with which words exactly are bothering you and why i should remove them?
